version: '3'
services:

  #PHP Service
  app_laravel:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:7.4-fpm
    container_name: app_laravel
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app_laravel
      SERVICE_TAGS: dev
    working_dir: /var/www
    networks:
      - app_laravel-network
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
  #Nginx Service
  webserver_laravel:
    image: nginx:alpine
    container_name: webserver_laravel
    restart: unless-stopped
    tty: true
    ports:
      - "81:80"
      - "444:443"
    networks:
      - app_laravel-network
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: volonter_db
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app_laravel-network
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf

#Docker Networks
networks:
  app_laravel-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
